import { StyleSheet } from 'react-native';

export const screenStyles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    gap: 18,
  },
  eyebrow: {
    color: '#fb923c',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.1,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  heroPanel: {
    backgroundColor: '#0b1f25',
    borderColor: '#144552',
    borderRadius: 28,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 22,
  },
  heroTitle: {
    color: '#f8fafc',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: -0.8,
    lineHeight: 38,
  },
  heroCopy: {
    color: '#d6e3ea',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 12,
  },
  heroStatsRow: {
    gap: 12,
    marginTop: 20,
  },
  sectionHeadline: {
    color: '#f8fafc',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
    marginBottom: 10,
  },
  sectionText: {
    color: '#d5dee5',
    fontSize: 15,
    lineHeight: 23,
  },
  sectionEmphasis: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
  },
  sectionSubtle: {
    color: '#8da2b4',
    fontSize: 13,
    fontWeight: '600',
  },
  runnerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#123341',
    borderRadius: 999,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatarText: {
    color: '#e0f2fe',
    fontSize: 18,
    fontWeight: '800',
  },
  runnerInfo: {
    flex: 1,
  },
  runnerName: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
  },
  runnerMeta: {
    color: '#9eb0bf',
    fontSize: 13,
    marginTop: 2,
  },
  vibeTag: {
    backgroundColor: '#1f2937',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  vibeTagText: {
    color: '#e5e7eb',
    fontSize: 12,
    fontWeight: '700',
  },
  boardRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  boardRank: {
    color: '#f59e0b',
    fontSize: 14,
    fontWeight: '800',
    width: 28,
  },
  boardName: {
    color: '#f8fafc',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
  },
  boardValue: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '700',
  },
  boardValueMuted: {
    color: '#7f93a3',
    fontSize: 13,
    width: 48,
  },
  trainingHero: {
    backgroundColor: '#12222f',
    borderRadius: 24,
    padding: 22,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  itemLine: {
    color: '#d5dee5',
    fontSize: 15,
    lineHeight: 22,
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: '#f97316',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 58,
  },
  primaryActionText: {
    color: '#fff7ed',
    fontSize: 18,
    fontWeight: '800',
  },
  mapMock: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  mapTile: {
    borderRadius: 10,
    height: 82,
    width: '30%',
  },
  tileOwned: {
    backgroundColor: '#1f9d55',
  },
  tileNeutral: {
    backgroundColor: '#64748b',
  },
  tileEnemy: {
    backgroundColor: '#ea580c',
  },
  legendRow: {
    flexDirection: 'row',
    gap: 18,
  },
  nearbyCard: {
    alignItems: 'center',
    backgroundColor: '#101f29',
    borderRadius: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  followButton: {
    backgroundColor: '#123341',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  followButtonText: {
    color: '#e0f2fe',
    fontSize: 13,
    fontWeight: '800',
  },
  chatInput: {
    backgroundColor: '#0b1520',
    borderColor: '#1f3445',
    borderRadius: 14,
    borderWidth: 1,
    color: '#f8fafc',
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chatRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: '#f97316',
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 84,
    paddingHorizontal: 12,
  },
  sendButtonText: {
    color: '#fff7ed',
    fontSize: 14,
    fontWeight: '800',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: '#3f1510',
    borderColor: '#7f1d1d',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 58,
  },
  dangerButtonText: {
    color: '#fecaca',
    fontSize: 18,
    fontWeight: '800',
  },
  infoRow: {
    backgroundColor: '#101f29',
    borderRadius: 16,
    padding: 14,
  },
  infoRowText: {
    color: '#d5dee5',
    fontSize: 14,
    lineHeight: 21,
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#123341',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  statusPillWarm: {
    backgroundColor: '#3a2510',
  },
  statusPillText: {
    color: '#dff7ff',
    fontSize: 12,
    fontWeight: '800',
  },
  profileBanner: {
    backgroundColor: '#17212b',
    borderRadius: 24,
    padding: 22,
  },
  profileHandle: {
    color: '#f59e0b',
    fontSize: 13,
    fontWeight: '800',
  },
  profileName: {
    color: '#f8fafc',
    fontSize: 30,
    fontWeight: '900',
    marginTop: 6,
  },
  profileMeta: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  mapCard: {
    backgroundColor: '#0d1720',
    borderColor: '#1c2a36',
    borderRadius: 22,
    borderWidth: 1,
    minHeight: 280,
    overflow: 'hidden',
  },
  mapSurface: {
    flex: 1,
    minHeight: 280,
  },
});
